version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/awsbitbucketcdci
permissions:
   - object: /var/www/html/awsbitbucketcdci
     pattern: "**"
     mode: 775
     owner: ubuntu	
     group: ubuntu
     type:
       - directory
       - file
hooks:
  BeforeInstall:
    - location: scripts/backup.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/commands.sh
      timeout: 300
      runas: root

